
export const projects = [
  {
    title: 'Forever Bee Honey',
    group: "Vitabiotics",
    detailsPage: "/projects/g2g",
    githubLink: "",
    image: '/images/products/4.jpg',
  
    id: 0,
  },
  {
    title: 'Wellman',
    group: "Vitabiotics",
     detailsPage: "/projects/mim",
    image: '/images/products/1.jpg',
    githubLink: "",
    id: 1,
  },
  {
    title: 'Juliet Eve',
    group: "Vitabiotics",
    detailsPage: "/projects/rxedu",
    image: '/images/products/2.jpg',
    githubLink: "",
    id: 2,
  },
  {
    title: 'WHEY PROTEIN',
     detailsPage: "/projects/rxeduNivea",
    group: "Nivea",
    image: '/images/products/1.jpg',
    githubLink: "",
    id: 3,
  },
  {
    title: 'Forever Aloe Vera Gel',
    group: "Vitabiotics",
    detailsPage: "/projects/bioplus",
    image: '/images/products/3.jpg',
    githubLink: "",
    id: 4,
  },
  {
    title: 'BTB',
    group: "Vitabiotics",
     detailsPage: "/projects/btb",
    image: '/images/products/4.jpg',
    githubLink: "",
    id: 5,
  },
  {
    title: 'Juli Juli',
    group: "Nivea",
     detailsPage: '/',
    image: '/images/products/2.jpg',
    githubLink: "",
    id: 6,
  },
];
